POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Mark",
    "lastName": "Doe",
    "email": "Mark@doe.com",
    "password": "Password123!"
}


POST http://localhost:3000/users/create-many
Content-Type: application/json


{
    "users" : [
    {
        "firstName": "Mark",
        "lastName": "Doe",
        "email": "mark@doe.com",
        "password": "password123!"
    },
        {
        "firstName": "tom",
        "lastName": "Doe",
        "email": "Tom@doe.com",
        "password": "password123!"
    }
    ] 
}

